
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  # - name: snowflake_sample_data
  #   description: 'A sample database provided by Snowflake'
  #   database: snowflake_sample_data
  #   schema: TPCDS_SF10TCL
  #   tables:
  #     - name: store_sales
  #       description: 'Store sales data'

#   # version: 2

# sources:
#   - name: snowflake_sample_data
#     description: 'A sample database provided by Snowflake'
#     database: snowflake_sample_data
#     schema: TPCDS_SF10TCL
#     tables:
#       - name: store_sales
#         description: 'Store sales data'
#       - name: catalog_sales
#       - name: web_sales
#       - name: item
#       - name: date_dim
#       - name: customer_address
#       - name: store
#       - name: customer

